version: '3.7'
services:

  configuration:
    image: mymax-configuration-service:0.0.1-SNAPSHOT
    container_name: configuration
    ports:
      - "8888:8888"
    restart: always   
    networks:
      - mymax-network

  discovery:
    image: mymax-discovery-service:0.0.1-SNAPSHOT
    container_name: discovery
    ports:
      - "8787:8787"
    restart: always
    environment:
      DISCOVERY_SERVER_NAME: discovery
      DISCOVERY_SERVER_PORT: 8787
      TZ: Asia/Jakarta
    depends_on:
      - configuration
    networks:
      - mymax-network    

  gateway:
    image: mymax-gateway-service:0.0.1-SNAPSHOT
    container_name: gateway
    ports:
      - "8443:8443"
    restart: always
    environment:
      DISCOVERY_SERVER_NAME: discovery
      DISCOVERY_SERVER_PORT: 8787
      TZ: Asia/Jakarta
    depends_on:
      - configuration
      - discovery
    networks:
      - mymax-network

  prospecting:
    image: mymax-prospecting-service:0.0.1-SNAPSHOT
    container_name: prospecting
    ports:
      - "8111:8111"
    restart: always
    environment:
      DISCOVERY_SERVER_NAME: discovery
      DISCOVERY_SERVER_PORT: 8787
      MYSQL_SERVER: host.docker.internal
      MYSQL_DB_NAME: mymaxdb
      MYSQL_USER: bybdbuser
      MYSQL_PWD: saudara123
      TZ: Asia/Jakarta
    depends_on:
      - configuration
      - discovery
    networks:
      - mymax-network

  progress:
    image: mymax-progress-service:0.0.1-SNAPSHOT
    container_name: progress
    ports:
      - "8211:8211"
    restart: always
    environment:
      DISCOVERY_SERVER_NAME: discovery
      DISCOVERY_SERVER_PORT: 8787
      MYSQL_SERVER: host.docker.internal
      MYSQL_DB_NAME: mymaxdb
      MYSQL_USER: bybdbuser
      MYSQL_PWD: saudara123
      TZ: Asia/Jakarta
    depends_on:
      - configuration
      - discovery
    networks:
      - mymax-network

  comment:
    image: mymax-comment-service:0.0.1-SNAPSHOT
    container_name: comment
    ports:
      - "8311:8311"
    restart: always
    environment:
      DISCOVERY_SERVER_NAME: discovery
      DISCOVERY_SERVER_PORT: 8787
      MYSQL_SERVER: host.docker.internal
      MYSQL_DB_NAME: mymaxdb
      MYSQL_USER: bybdbuser
      MYSQL_PWD: saudara123
      TZ: Asia/Jakarta
    depends_on:
      - configuration
      - discovery
    networks:
      - mymax-network

# Networks to be created to facilitate communication between containers
networks:
  mymax-network:
    name: mymax-network