version: '3.7'
services:
  
  rabbitmq:
    image: rabbitmq:3.8.2-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - dimix-network
        
  configuration:
    image: dimix/dimix-configuration-server:0.0.1-SNAPSHOT
    container_name: configuration
    ports:
      - "8888:8888"
    restart: always   
    networks:
      - dimix-network
  
  discovery:
    image: dimix/dimix-discovery-server:0.0.1-SNAPSHOT
    container_name: discovery
    ports:
      - "8787:8787"
    restart: always
    environment:
      DISCOVERY_SERVER_NAME: discovery
      DISCOVERY_SERVER_PORT: 8787
      TZ: Asia/Jakarta
    depends_on:
      - configuration
    networks:
      - dimix-network    
  
  gateway:
    image: dimix/dimix-gateway-server:0.0.1-SNAPSHOT
    #container_name: gateway
    ports:
      - "8443-8445:8443"
    restart: always
    environment:
      DISCOVERY_SERVER_NAME: discovery
      DISCOVERY_SERVER_PORT: 8787
      TZ: Asia/Jakarta
    depends_on:
      - configuration
      - discovery
    networks:
      - dimix-network
  
  authorization:
    image: dimix/dimix-authorization-server:0.0.1-SNAPSHOT
    container_name: authorization
    ports:
      - "8111:8111"
    restart: always
    environment:
      DISCOVERY_SERVER_NAME: discovery
      DISCOVERY_SERVER_PORT: 8787
      MYSQL_SERVER: host.docker.internal
      MYSQL_DB_NAME: dimixdb
      MYSQL_USER: bybdbuser
      MYSQL_PWD: saudara123
      TZ: Asia/Jakarta
    depends_on:
      - configuration
      - discovery
    networks:
      - dimix-network
      
  testing:
    image: dimix/dimix-testing-service:0.0.1-SNAPSHOT
    #container_name: submission
    ports:
      - "9911-9915:9911"
    restart: always
    environment:
      DISCOVERY_SERVER_NAME: discovery
      DISCOVERY_SERVER_PORT: 8787
      TZ: Asia/Jakarta
    depends_on:
      - configuration
      - discovery
    networks:
      - dimix-network
      
  
      
  
  
# Networks to be created to facilitate communication between containers
networks:
  dimix-network:
    name: dimix-network